#DATA TYPE

1. DB   (DEFINE BYTE)
2. DW   (DEFINE WORD)
3. DD   (DEFINE DOUBLEWORD)
4. DQ   (DEFINE QUADWORD)

DECLARATION

        VAR_NAME     TYPE    VALUE
            A         DB       9
         MESSAGE      DB  'HELLOWORLD'
HERE A DATABYTE MEMORY IS ALLOCATED FOR EACH CHARACTER
